### ISSUE TITLE
Add supply catalog table

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-configs#89]
- [ ] Add supply catalog table as defined in [here](https://docs.google.com/document/d/1KSZtDIAVgDjskbkGOg4W6FLIVMW9ubt2VHwxdLqAUrI/edit?ts=5f29a5aa#heading=h.jribshv7sh6c)

- [ ] The table should store most of the data in json with only the search fields being saved on their own columns

**Comment by rehammuzzamil** [comment]
As per the issue details and discussion with @githengi , most of the fields should be stored in JSON, and for now, we are allowing search by product name, type, and a unique id. We will also add field of server_version.
